spring:
  application:
    name: manager-finances
  datasource:
    url: jdbc:postgresql://localhost:5432/manager_finances
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode:
      continue-on-error: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    br.com.managerfinances.api: DEBUG

jwt:
    secret: b4nAVoHag2vgsP9eNAzv3hsfxVUXZ9mRfUt7e6PWjKLcDpgTYqZjZhmNkX2NHnPv
    expiration: 86400000
google:
  client:
    id: 768173493849-knip8nnc3c2lioml227fo5ubdmcqe8pb.apps.googleusercontent.com

server:
  port: 8085